//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalCrossingNewHorizons.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COM
    {
        public long com_id { get; set; }
        public string com_name { get; set; }
        public string com_detail { get; set; }
        public byte del_flag { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_user { get; set; }
        public System.DateTime update_date { get; set; }
        public string update_user { get; set; }
    }
}
